### ISSUE TITLE
Suggestion for creating the prerequisite directory structure in AssetInstance

### ISSUE THREAD

**Issue by MostHated** [vertxxyz/Vertx.Utilities#1]
Not sure if you are into it, but I am typically much more fond of the below type of approach for creating the directory structure for an asset via a provided relative path.

I only bring this up because I was just checking out the library and right off the bat I received this error message:

```cs
Parent directory must exist before creating asset at Assets/instanceid/Resources/TestAsset.asset.
```
So I adjusted it locally to the way I typically like to do it, and wanted to share, just in case you find it useful. 

```cs

private const string assetFolder = "Assets";
...

public static T CreateInstanceInProject(string fileName, string folder, T instance = null)
{
    if (!fileName.Contains("."))
        fileName += ".asset";

    var basePath = folder.StartsWith(assetFolder)
        ? Application.dataPath.Substring(0, Application.dataPath.Length - assetFolder.Length)
        : Application.dataPath;

    var assetPath = Path.Combine(basePath, folder);

    if (!Directory.Exists(assetPath))
        Directory.CreateDirectory(assetPath);
    
    string path = $"{folder}/{fileName}";
    if (instance == null)
        instance = CreateInstance<T>();
    AssetDatabase.CreateAsset(instance, path);
    AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceSynchronousImport);
    return instance;
}

```

**Comment by vertxxyz** [comment]
This has fallen by the wayside for some time. Seeing as this feature is now built-in with [ScriptableSingleton](https://docs.unity3d.com/ScriptReference/ScriptableSingleton_1.html), I will be removing it from future releases.
